# Generated by Django 5.2.14 on 2026-05-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sundaydrive',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='sundaydrive',
            name='longitude',
        ),
        migrations.AddField(
            model_name='sundaydrive',
            name='end_location_link',
            field=models.URLField(blank=True, help_text='Paste the Google Maps Share Link for the end (if different).', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sundaydrive',
            name='start_location_link',
            field=models.URLField(blank=True, help_text='Paste the Google Maps Share Link for the start.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sundaydrive',
            name='meeting_point',
            field=models.CharField(help_text="e.g., 'Cubbon Park Entrance'", max_length=255),
        ),
    ]
