# Generated by Django 5.2.14 on 2026-05-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0002_remove_sundaydrive_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sundaydrive',
            name='end_point',
            field=models.CharField(blank=True, help_text="End location text, e.g., 'Lalbagh Botanical Garden'. Leave blank for a single-location drive.", max_length=255, null=True),
        ),
    ]
